/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javacalculator;
/**
 *
 * @author IIseichi
 */
public class mainCalculator extends javax.swing.JFrame {

    /**
     * Creates new form mainCalculator
     */
    
    double num1;
    double num2;
    double result;
    String Operator;
    
    private boolean isPowerOn = true;
            
    public mainCalculator() {
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setSize(300,450);
        setLocationRelativeTo(null);
        initComponents();
        output.setEditable(true);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private void EnterNumbers (String enterNumbers) {
        String Nums = output.getText() + enterNumbers;
        output.setText(Nums);
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        output = new javax.swing.JTextField();
        btnPower = new javax.swing.JButton();
        btnNegativeSign = new javax.swing.JButton();
        btnPowerOfX = new javax.swing.JButton();
        btnSquared = new javax.swing.JButton();
        btnSquareRoot = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btnDivide = new javax.swing.JButton();
        btnMultiply = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btnSubtract = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btnEqual = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnReminder = new javax.swing.JButton();
        btnDecimal = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        icon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        output.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        output.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel1.add(output);
        output.setBounds(20, 50, 260, 130);

        btnPower.setBorder(null);
        btnPower.setBorderPainted(false);
        btnPower.setContentAreaFilled(false);
        btnPower.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPowerActionPerformed(evt);
            }
        });
        jPanel1.add(btnPower);
        btnPower.setBounds(240, 210, 40, 20);

        btnNegativeSign.setBorder(null);
        btnNegativeSign.setBorderPainted(false);
        btnNegativeSign.setContentAreaFilled(false);
        btnNegativeSign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNegativeSignActionPerformed(evt);
            }
        });
        jPanel1.add(btnNegativeSign);
        btnNegativeSign.setBounds(190, 210, 40, 20);

        btnPowerOfX.setBorder(null);
        btnPowerOfX.setBorderPainted(false);
        btnPowerOfX.setContentAreaFilled(false);
        btnPowerOfX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPowerOfXActionPerformed(evt);
            }
        });
        jPanel1.add(btnPowerOfX);
        btnPowerOfX.setBounds(130, 210, 40, 20);

        btnSquared.setBorder(null);
        btnSquared.setBorderPainted(false);
        btnSquared.setContentAreaFilled(false);
        btnSquared.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSquaredActionPerformed(evt);
            }
        });
        jPanel1.add(btnSquared);
        btnSquared.setBounds(70, 210, 40, 20);

        btnSquareRoot.setBorder(null);
        btnSquareRoot.setBorderPainted(false);
        btnSquareRoot.setContentAreaFilled(false);
        btnSquareRoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSquareRootActionPerformed(evt);
            }
        });
        jPanel1.add(btnSquareRoot);
        btnSquareRoot.setBounds(10, 210, 50, 20);

        btnClear.setBorder(null);
        btnClear.setBorderPainted(false);
        btnClear.setContentAreaFilled(false);
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel1.add(btnClear);
        btnClear.setBounds(230, 260, 60, 30);

        btnDel.setBorder(null);
        btnDel.setBorderPainted(false);
        btnDel.setContentAreaFilled(false);
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });
        jPanel1.add(btnDel);
        btnDel.setBounds(170, 250, 60, 40);

        btn9.setBorder(null);
        btn9.setBorderPainted(false);
        btn9.setContentAreaFilled(false);
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        jPanel1.add(btn9);
        btn9.setBounds(120, 250, 40, 50);

        btn8.setBorder(null);
        btn8.setBorderPainted(false);
        btn8.setContentAreaFilled(false);
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        jPanel1.add(btn8);
        btn8.setBounds(70, 250, 40, 50);

        btn7.setBorder(null);
        btn7.setBorderPainted(false);
        btn7.setContentAreaFilled(false);
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        jPanel1.add(btn7);
        btn7.setBounds(10, 250, 40, 50);

        btnDivide.setBorder(null);
        btnDivide.setBorderPainted(false);
        btnDivide.setContentAreaFilled(false);
        btnDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivideActionPerformed(evt);
            }
        });
        jPanel1.add(btnDivide);
        btnDivide.setBounds(240, 310, 40, 40);

        btnMultiply.setBorder(null);
        btnMultiply.setBorderPainted(false);
        btnMultiply.setContentAreaFilled(false);
        btnMultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplyActionPerformed(evt);
            }
        });
        jPanel1.add(btnMultiply);
        btnMultiply.setBounds(170, 310, 60, 40);

        btn6.setBorder(null);
        btn6.setBorderPainted(false);
        btn6.setContentAreaFilled(false);
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        jPanel1.add(btn6);
        btn6.setBounds(120, 310, 40, 40);

        btn5.setBorder(null);
        btn5.setBorderPainted(false);
        btn5.setContentAreaFilled(false);
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        jPanel1.add(btn5);
        btn5.setBounds(70, 310, 40, 40);

        btn4.setBorder(null);
        btn4.setBorderPainted(false);
        btn4.setContentAreaFilled(false);
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        jPanel1.add(btn4);
        btn4.setBounds(10, 310, 40, 40);

        btnSubtract.setBorder(null);
        btnSubtract.setBorderPainted(false);
        btnSubtract.setContentAreaFilled(false);
        btnSubtract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubtractActionPerformed(evt);
            }
        });
        jPanel1.add(btnSubtract);
        btnSubtract.setBounds(170, 370, 60, 40);

        btn3.setBorder(null);
        btn3.setBorderPainted(false);
        btn3.setContentAreaFilled(false);
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        jPanel1.add(btn3);
        btn3.setBounds(120, 370, 40, 40);

        btn2.setBorder(null);
        btn2.setBorderPainted(false);
        btn2.setContentAreaFilled(false);
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        jPanel1.add(btn2);
        btn2.setBounds(70, 370, 40, 40);

        btn1.setBorder(null);
        btn1.setBorderPainted(false);
        btn1.setContentAreaFilled(false);
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn1);
        btn1.setBounds(10, 370, 40, 40);

        btnEqual.setBorder(null);
        btnEqual.setBorderPainted(false);
        btnEqual.setContentAreaFilled(false);
        btnEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEqualActionPerformed(evt);
            }
        });
        jPanel1.add(btnEqual);
        btnEqual.setBounds(240, 360, 40, 110);

        btnAdd.setBorder(null);
        btnAdd.setBorderPainted(false);
        btnAdd.setContentAreaFilled(false);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd);
        btnAdd.setBounds(170, 430, 60, 40);

        btnReminder.setBorder(null);
        btnReminder.setBorderPainted(false);
        btnReminder.setContentAreaFilled(false);
        btnReminder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReminderActionPerformed(evt);
            }
        });
        jPanel1.add(btnReminder);
        btnReminder.setBounds(120, 430, 40, 40);

        btnDecimal.setBorder(null);
        btnDecimal.setBorderPainted(false);
        btnDecimal.setContentAreaFilled(false);
        btnDecimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDecimalActionPerformed(evt);
            }
        });
        jPanel1.add(btnDecimal);
        btnDecimal.setBounds(70, 430, 40, 40);

        btn0.setBorder(null);
        btn0.setBorderPainted(false);
        btn0.setContentAreaFilled(false);
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });
        jPanel1.add(btn0);
        btn0.setBounds(10, 430, 40, 40);

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("background.png"))); // NOI18N
        jPanel1.add(icon);
        icon.setBounds(0, 0, 300, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        // TODO add your handling code here:
        EnterNumbers("8");
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // TODO add your handling code here:
        EnterNumbers("5");
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        // TODO add your handling code here:
        EnterNumbers("9");
    }//GEN-LAST:event_btn9ActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        num1 = Double.parseDouble(output.getText());
        Operator = "+";
        output.setText(output.getText() + " + ");
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        output.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnSquareRootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSquareRootActionPerformed
        // TODO add your handling code here:
         double val = Double.parseDouble(output.getText());
         if (val >= 0) {
            double sqrt = Math.sqrt(val);
            output.setText(String.valueOf(sqrt));
        } else {
            output.setText("Error");
        }
    }//GEN-LAST:event_btnSquareRootActionPerformed

    private void btnMultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplyActionPerformed
        // TODO add your handling code here:
        num1 = Double.parseDouble(output.getText());
        Operator = "*";
        output.setText(output.getText() + " * ");
    }//GEN-LAST:event_btnMultiplyActionPerformed

    private void btnDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivideActionPerformed
        // TODO add your handling code here:
        num1 = Double.parseDouble(output.getText());
        Operator = "/";
        output.setText(output.getText() + " / ");
    }//GEN-LAST:event_btnDivideActionPerformed

    private void btnEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEqualActionPerformed
        // TODO add your handling code here:
        String[] parts = output.getText().split(" ");

        if (parts.length == 3) {
            try {
                num1 = Double.parseDouble(parts[0]);
                Operator = parts[1];
                num2 = Double.parseDouble(parts[2]);

                switch (Operator) {
                    case "+":
                        result = num1 + num2;
                        break;
                    case "-":
                        result = num1 - num2;
                        break;
                    case "*":
                        result = num1 * num2;
                        break;
                    case "/":
                        result = num2 != 0 ? num1 / num2 : Double.NaN;
                        break;
                    case "%":
                        if (num2 != 0) {
                            result = num1 % num2;
                        } else {
                            output.setText("Cannot divide by zero!");
                            return;
                        }
                        break;
                    case "^":
                        result = Math.pow(num1, num2);
                        break;
                    default:
                        output.setText("Unknown operator");
                        return;
                }

                if (Operator.equals("%")) {
                    output.setText("Remainder: " + String.format("%8f", result).replaceAll("\\.?0+$", ""));
                } else {
                output.setText(String.format("%8f", result).replaceAll("\\.?0+$", ""));
                }

            } catch (NumberFormatException e) {
                output.setText("Invalid number");
            }
        } else {
            output.setText("Invalid input");
        }
    }//GEN-LAST:event_btnEqualActionPerformed

    private void btnSubtractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubtractActionPerformed
        // TODO add your handling code here:
        num1 = Double.parseDouble(output.getText());
        Operator = "-";
        output.setText(output.getText() + " - ");
    }//GEN-LAST:event_btnSubtractActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        // TODO add your handling code here:
        EnterNumbers("7");
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
        EnterNumbers("4");
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        EnterNumbers("1");
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        // TODO add your handling code here:
        EnterNumbers("6");
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
        EnterNumbers("2");
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
        EnterNumbers("3");
    }//GEN-LAST:event_btn3ActionPerformed

    private void btnReminderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReminderActionPerformed
        // TODO add your handling code here:
        num1 = Double.parseDouble(output.getText());
        Operator = "%";
        output.setText(output.getText() + " % ");
    }//GEN-LAST:event_btnReminderActionPerformed

    private void btnDecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDecimalActionPerformed
        // TODO add your handling code here:
        if (!output.getText().contains(".")){
            output.setText(output.getText() + ".");
        }
    }//GEN-LAST:event_btnDecimalActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        // TODO add your handling code here:
        EnterNumbers("0");
    }//GEN-LAST:event_btn0ActionPerformed

    private void btnNegativeSignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNegativeSignActionPerformed
        // TODO add your handling code here:
        String text = output.getText();
        
        if (Operator == null || Operator.isEmpty() || !text.contains(" " + Operator + " ")) {
            double val = Double.parseDouble(text);
            val *= -1;
            output.setText(String.valueOf(val));
        } else {
            String[] parts = text.split(" \\" + Operator + " ");
            
            if (parts.length == 2) {
                String left = parts[0];
                String right = parts[1];
                
                if (!right.isEmpty()) {
                
                    try {
                        double val = Double.parseDouble(right);
                        val *= -1;
                        output.setText(left + " " + Operator + " " + val);
                    } catch (NumberFormatException e) {
                    output.setText("Error");
                    }
                }
            }
        }
    }//GEN-LAST:event_btnNegativeSignActionPerformed

    private void btnSquaredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSquaredActionPerformed
        // TODO add your handling code here:
        double val = Double.parseDouble(output.getText());
        double square = val * val;
        output.setText(String.valueOf(square));
    }//GEN-LAST:event_btnSquaredActionPerformed

    private void btnPowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPowerActionPerformed
        // TODO add your handling code here:
        isPowerOn = !isPowerOn;
        output.setText(isPowerOn ? "" : "OFF");
        
        btn0.setEnabled(isPowerOn);
        btn1.setEnabled(isPowerOn);
        btn2.setEnabled(isPowerOn);
        btn3.setEnabled(isPowerOn);
        btn4.setEnabled(isPowerOn);
        btn5.setEnabled(isPowerOn);
        btn6.setEnabled(isPowerOn);
        btn7.setEnabled(isPowerOn);
        btn8.setEnabled(isPowerOn);
        btn9.setEnabled(isPowerOn);
        btnReminder.setEnabled(isPowerOn);
        btnAdd.setEnabled(isPowerOn);
        btnSubtract.setEnabled(isPowerOn);
        btnMultiply.setEnabled(isPowerOn);
        btnDivide.setEnabled(isPowerOn);
        btnEqual.setEnabled(isPowerOn);
        btnClear.setEnabled(isPowerOn);
        btnDel.setEnabled(isPowerOn);
        btnDecimal.setEnabled(isPowerOn);
        btnNegativeSign.setEnabled(isPowerOn);
        btnPowerOfX.setEnabled(isPowerOn);
        btnSquareRoot.setEnabled(isPowerOn);
        btnSquared.setEnabled(isPowerOn);
        btnPower.setEnabled(true);
    }//GEN-LAST:event_btnPowerActionPerformed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        // TODO add your handling code here:
        String del = null;
        
        if (output.getText().length()>0){
            StringBuilder sb = new StringBuilder(output.getText());
            sb.deleteCharAt(output.getText().length() - 1);
            del = sb.toString();
            output.setText(del);
        }
    }//GEN-LAST:event_btnDelActionPerformed

    private void btnPowerOfXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPowerOfXActionPerformed
        // TODO add your handling code here:
        num1 = Double.parseDouble(output.getText());
        Operator = "^"; 
        output.setText(output.getText() + " ^ ");
    }//GEN-LAST:event_btnPowerOfXActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainCalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDecimal;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnDivide;
    private javax.swing.JButton btnEqual;
    private javax.swing.JButton btnMultiply;
    private javax.swing.JButton btnNegativeSign;
    private javax.swing.JButton btnPower;
    private javax.swing.JButton btnPowerOfX;
    private javax.swing.JButton btnReminder;
    private javax.swing.JButton btnSquareRoot;
    private javax.swing.JButton btnSquared;
    private javax.swing.JButton btnSubtract;
    private javax.swing.JLabel icon;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField output;
    // End of variables declaration//GEN-END:variables
}
